spring:
  application:
    name: lol
  profiles:
    active: local
    include:
      - database

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      fail-on-null-for-primitives: true

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

management:
  server:
    port: 8888
  health:
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,httpTrace,prometheus
